[workspace]
members = [
    "lib",
    "program",
    "script",
]
resolver = "2"

[workspace.dependencies]
sdk = { git = "https://github.com/hyli-org/hyli", package = "hyle-contract-sdk", tag = "v0.13.0-rc.1" }
client-sdk = { git = "https://github.com/hyli-org/hyli", package = "hyle-client-sdk", tag = "v0.13.0-rc.1"  }

